<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Model;

use Diaporamas\Model\Base\Diaporama as BaseDiaporama;

/**
 * Class Diaporama
 * @package Diaporamas\Model
 */
class Diaporama extends BaseDiaporama
{
}
