<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Model;

use Diaporamas\Model\Base\DiaporamaType as BaseDiaporamaType;

/**
 * Class DiaporamaType
 * @package Diaporamas\Model
 */
class DiaporamaType extends BaseDiaporamaType
{
}
