<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Model;

use Diaporamas\Model\Base\DiaporamaTypeI18n as BaseDiaporamaTypeI18n;

/**
 * Class DiaporamaTypeI18n
 * @package Diaporamas\Model
 */
class DiaporamaTypeI18n extends BaseDiaporamaTypeI18n
{
}
