<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Model;

use Diaporamas\Model\Base\Diaporama as BaseDiaporama;

/**
 * Class Diaporama
 * @package Diaporamas\Model
 */
class Diaporama extends BaseDiaporama
{
    public function getEntityTitle()
    {
        $code = DiaporamaType::getCodeById($this->diaporama_type_id, true);
        $queryClass = '\\Thelia\\Model\\'.$code.'Query';
        return $queryClass::create()->findOneById($this->entity_id)->getTitle();
    }
}
