<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Model;

use Diaporamas\Model\Base\DiaporamaImage as BaseDiaporamaImage;
use Thelia\Model\Tools\ModelEventDispatcherTrait;
use Thelia\Model\Tools\PositionManagementTrait;
use Propel\Runtime\Connection\ConnectionInterface;

/**
 * Class DiaporamaImage
 * @package Diaporamas\Model
 */
class DiaporamaImage extends BaseDiaporamaImage
{
    use ModelEventDispatcherTrait;
    use PositionManagementTrait;

    public function preInsert(ConnectionInterface $con = null)
    {
        $this->setPosition($this->getNextPosition());

        return true;
    }
}
