<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Model;

use Diaporamas\Model\Base\DiaporamaImageI18n as BaseDiaporamaImageI18n;
use Thelia\Model\Tools\I18nTimestampableTrait;

/**
 * Class DiaporamaImageI18n
 * @package Diaporamas\Model
 */
class DiaporamaImageI18n extends BaseDiaporamaImageI18n
{
    use I18nTimestampableTrait;
}
