<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Model;

use Diaporamas\Model\Base\DiaporamaI18n as BaseDiaporamaI18n;
use Thelia\Model\Tools\I18nTimestampableTrait;

/**
 * Class DiaporamaI18n
 * @package Diaporamas\Model
 */
class DiaporamaI18n extends BaseDiaporamaI18n
{
    use I18nTimestampableTrait;
}
