<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Model;

use Diaporamas\Model\Base\DiaporamaType as BaseDiaporamaType;

/**
 * Class DiaporamaType
 * @package Diaporamas\Model
 */
class DiaporamaType extends BaseDiaporamaType
{
    public static function getAllCodes($ucfirst = false)
    {
        $codes = DiaporamaTypeQuery::create()
            ->select(array('DiaporamaType.Id', 'DiaporamaType.Code'))
            ->orderBy('DiaporamaType.Id')
            ->find()
            ->toKeyValue('DiaporamaType.Id', 'DiaporamaType.Code')
        ;

        if ($ucfirst) {
            foreach ($codes as &$code) {
                $code = ucfirst($code);
            }
        }

        return $codes;
    }

    public static function getCodeById($id, $ucfirst = false)
    {
        $code = DiaporamaTypeQuery::create()->findOneById($id);
        $code = $code->getCode();
        $ucfirst and $code = ucfirst($code);
        return $code;
    }
}
