<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Action;

use Diaporamas\Action\Base\DiaporamaAction as  BaseDiaporamaAction;

/**
 * Class DiaporamaAction
 * @package Diaporamas\Action
 */
class DiaporamaAction extends BaseDiaporamaAction
{
}
