<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Action;

use Diaporamas\Action\Base\DiaporamaImageAction as  BaseDiaporamaImageAction;

/**
 * Class DiaporamaImageAction
 * @package Diaporamas\Action
 */
class DiaporamaImageAction extends BaseDiaporamaImageAction
{
}
