<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Action;

use Diaporamas\Action\Base\DiaporamaTypeAction as  BaseDiaporamaTypeAction;

/**
 * Class DiaporamaTypeAction
 * @package Diaporamas\Action
 */
class DiaporamaTypeAction extends BaseDiaporamaTypeAction
{
}
