<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Form\Type;

use Diaporamas\Form\Type\Base\DiaporamaIdType as BaseDiaporamaIdType;

/**
 * Class Diaporama
 * @package Diaporamas\Form
 */
class DiaporamaIdType extends BaseDiaporamaIdType
{
}
