<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Form\Type;

use Diaporamas\Form\Type\Base\DiaporamaImageIdType as BaseDiaporamaImageIdType;

/**
 * Class DiaporamaImage
 * @package Diaporamas\Form
 */
class DiaporamaImageIdType extends BaseDiaporamaImageIdType
{
}
