<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Form\Type;

use Diaporamas\Form\Type\Base\DiaporamaTypeIdType as BaseDiaporamaTypeIdType;

/**
 * Class DiaporamaType
 * @package Diaporamas\Form
 */
class DiaporamaTypeIdType extends BaseDiaporamaTypeIdType
{
}
