<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas;

use Symfony\Component\Filesystem\Filesystem;
use Thelia\Model\ConfigQuery;
use Thelia\Module\BaseModule;
use Propel\Runtime\Connection\ConnectionInterface;
use Thelia\Install\Database;

/**
 * Class Diaporamas
 * @package Diaporamas
 */
class Diaporamas extends BaseModule
{
    const MESSAGE_DOMAIN = "diaporamas";
    const BO_MESSAGE_DOMAIN = "diaporamas.bo.default";
    const ROUTER = "router.diaporamas";

    public function postActivation(ConnectionInterface $con = null)
    {
        $database = new Database($con);
        $database->insertSql(null, [__DIR__ . "/Config/create.sql", __DIR__ . "/Config/insert.sql"]);

        $fs = new Filesystem();
        $diaporamaImagesFolder = Diaporamas::getDiaporamaImagesFolder();
        !$fs->exists($diaporamaImagesFolder) and $fs->mkdir($diaporamaImagesFolder);
    }

    public static function getDiaporamaImagesFolder()
    {
        return sprintf(
            "%s%s/diaporama",
            THELIA_ROOT,
            ConfigQuery::read('images_library_path', 'local'.DS.'media'.DS.'images')
        );
    }

    public function destroy(ConnectionInterface $con = null, $deleteModuleData = false)
    {
        if ($deleteModuleData) {
            $fs = new Filesystem();
            $diaporamaImagesFolder = Diaporamas::getDiaporamaImagesFolder();
            $fs->exists($diaporamaImagesFolder) and $fs->remove($diaporamaImagesFolder);
        }

        return parent::destroy($con, $deleteModuleData);
    }
}
