<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Event;

use Diaporamas\Event\Base\DiaporamaEvents as BaseDiaporamaEvents;

/**
 * Class DiaporamaEvents
 * @package Diaporamas\Event
 */
class DiaporamaEvents extends BaseDiaporamaEvents
{
    const DIAPORAMA_HTML = 'diaporamas.diaporama.html';
    const DIAPORAMA_PARSE = 'diaporamas.diaporama.replace_shortcodes';
}
