<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Event;

use Diaporamas\Event\Base\DiaporamaImageEvent as BaseDiaporamaImageEvent;

/**
 * Class DiaporamaImageEvent
 * @package Diaporamas\Event
 */
class DiaporamaImageEvent extends BaseDiaporamaImageEvent
{
}
