<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Event;

use Diaporamas\Event\Base\DiaporamaImageEvents as BaseDiaporamaImageEvents;

/**
 * Class DiaporamaImageEvents
 * @package Diaporamas\Event
 */
class DiaporamaImageEvents extends BaseDiaporamaImageEvents
{
}
