<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Event;

use Diaporamas\Event\Base\DiaporamaEvent as BaseDiaporamaEvent;

/**
 * Class DiaporamaEvent
 * @package Diaporamas\Event
 */
class DiaporamaEvent extends BaseDiaporamaEvent
{
}
