<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Event;

use Diaporamas\Event\Base\DiaporamaTypeEvents as BaseDiaporamaTypeEvents;

/**
 * Class DiaporamaTypeEvents
 * @package Diaporamas\Event
 */
class DiaporamaTypeEvents extends BaseDiaporamaTypeEvents
{
}
