<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Event;

use Diaporamas\Event\Base\DiaporamaTypeEvent as BaseDiaporamaTypeEvent;

/**
 * Class DiaporamaTypeEvent
 * @package Diaporamas\Event
 */
class DiaporamaTypeEvent extends BaseDiaporamaTypeEvent
{
}
