<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Form\Base;

use Diaporamas\Form\DiaporamaImageCreateForm as ChildDiaporamaImageCreateForm;
use Diaporamas\Form\Type\DiaporamaImageIdType;

/**
 * Class DiaporamaImageForm
 * @package Diaporamas\Form
 * @author TheliaStudio
 */
class DiaporamaImageUpdateForm extends ChildDiaporamaImageCreateForm
{
    const FORM_NAME = "diaporama_image_update";

    public function buildForm()
    {
        parent::buildForm();

        $this->formBuilder
            ->add("id", DiaporamaImageIdType::TYPE_NAME)
            ->remove("visible")
        ;
    }
}
