<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Form\Base;

use Diaporamas\Diaporamas;
use Thelia\Form\BaseForm;
use Symfony\Component\Validator\Constraints\NotBlank;

/**
 * Class DiaporamaImageCreateForm
 * @package Diaporamas\Form\Base
 * @author TheliaStudio
 */
class DiaporamaImageCreateForm extends BaseForm
{
    const FORM_NAME = "diaporama_image_create";

    public function buildForm()
    {
        $translationKeys = $this->getTranslationKeys();
        $fieldsIdKeys = $this->getFieldsIdKeys();

        $this->addDiaporamaIdField($translationKeys, $fieldsIdKeys);
        $this->addDiaporamaTypeIdField($translationKeys, $fieldsIdKeys);
        $this->addEntityIdField($translationKeys, $fieldsIdKeys);
    }

    protected function addDiaporamaIdField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("diaporama_id", "integer", array(
            "label" => $this->translator->trans($this->readKey("diaporama_id", $translationKeys), [], Diaporamas::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("diaporama_id", $fieldsIdKeys)],
            "required" => true,
            "constraints" => array(
                new NotBlank(),
            ),
            "attr" => array(
            )
        ));
    }

    protected function addDiaporamaTypeIdField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("diaporama_type_id", "integer", array(
            "label" => $this->translator->trans($this->readKey("diaporama_type_id", $translationKeys), [], Diaporamas::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("diaporama_type_id", $fieldsIdKeys)],
            "required" => true,
            "constraints" => array(
                new NotBlank(),
            ),
            "attr" => array(
            )
        ));
    }

    protected function addEntityIdField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("entity_id", "integer", array(
            "label" => $this->translator->trans($this->readKey("entity_id", $translationKeys), [], Diaporamas::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("entity_id", $fieldsIdKeys)],
            "required" => true,
            "constraints" => array(
                new NotBlank(),
            ),
            "attr" => array(
            )
        ));
    }

    public function getName()
    {
        return static::FORM_NAME;
    }

    public function readKey($key, array $keys, $default = '')
    {
        if (isset($keys[$key])) {
            return $keys[$key];
        }

        return $default;
    }

    public function getTranslationKeys()
    {
        return array();
    }

    public function getFieldsIdKeys()
    {
        return array(
            "diaporama_id" => "diaporama_image_diaporama_id",
            "diaporama_type_id" => "diaporama_image_diaporama_type_id",
            "entity_id" => "diaporama_image_entity_id",
            "position" => "diaporama_image_position",
        );
    }
}
