<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Form\Base;

use Diaporamas\Form\DiaporamaCreateForm as ChildDiaporamaCreateForm;
use Diaporamas\Form\Type\DiaporamaIdType;

/**
 * Class DiaporamaForm
 * @package Diaporamas\Form
 * @author TheliaStudio
 */
class DiaporamaUpdateForm extends ChildDiaporamaCreateForm
{
    const FORM_NAME = "diaporama_update";

    public function buildForm()
    {
        parent::buildForm();

        $this->formBuilder
            ->add("id", DiaporamaIdType::TYPE_NAME)
        ;
    }
}
