<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Form\Base;

use Diaporamas\Form\DiaporamaTypeCreateForm as ChildDiaporamaTypeCreateForm;
use Diaporamas\Form\Type\DiaporamaTypeIdType;

/**
 * Class DiaporamaTypeForm
 * @package Diaporamas\Form
 * @author TheliaStudio
 */
class DiaporamaTypeUpdateForm extends ChildDiaporamaTypeCreateForm
{
    const FORM_NAME = "diaporama_type_update";

    public function buildForm()
    {
        parent::buildForm();

        $this->formBuilder
            ->add("id", DiaporamaTypeIdType::TYPE_NAME)
        ;
    }
}
