<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Loop;

use Diaporamas\Loop\Base\Diaporama as BaseDiaporamaLoop;

/**
 * Class Diaporama
 * @package Diaporamas\Loop
 */
class Diaporama extends BaseDiaporamaLoop
{
    /**
     * You may now add your own logic
     */
}
