<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Loop;

use Diaporamas\Loop\Base\DiaporamaType as BaseDiaporamaTypeLoop;

/**
 * Class DiaporamaType
 * @package Diaporamas\Loop
 */
class DiaporamaType extends BaseDiaporamaTypeLoop
{
    /**
     * You may now add your own logic
     */
}
