<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Loop;

use Diaporamas\Loop\Base\Diaporama as BaseDiaporamaLoop;
use Thelia\Core\Template\Element\LoopResultRow;

/**
 * Class Diaporama
 * @package Diaporamas\Loop
 */
class Diaporama extends BaseDiaporamaLoop
{
    /**
     * You may now add your own logic
     */

    protected function addMoreResults(LoopResultRow $row, \Diaporamas\Model\Diaporama $entryObject)
    {

        $row
            ->set("DIAPORAMA_TYPE_TITLE", ucfirst($entryObject->getDiaporamaType()->getTitle()))
            ->set("ENTITY_TITLE", $entryObject->getEntityTitle())
            ->set("ENTITY_PATH", $entryObject->getDiaporamaType()->getPath())
        ;
    }
}
