<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Loop;

use Diaporamas\Loop\Base\DiaporamaImage as BaseDiaporamaImageLoop;

/**
 * Class DiaporamaImage
 * @package Diaporamas\Loop
 */
class DiaporamaImage extends BaseDiaporamaImageLoop
{
    /**
     * You may now add your own logic
     */
}
