<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Form;

use Diaporamas\Form\Base\DiaporamaImageUpdateForm as BaseDiaporamaImageUpdateForm;

/**
 * Class DiaporamaImageUpdateForm
 * @package Diaporamas\Form
 */
class DiaporamaImageUpdateForm extends BaseDiaporamaImageUpdateForm
{
    public function getTranslationKeys()
    {
        return array(
            "id" => "id",
            "diaporama_id" => "diaporama_id",
            "diaporama_type_id" => "diaporama_type_id",
            "entity_id" => "entity_id",
            "position" => "position",
        );
    }
}
