<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Form;

use Diaporamas\Form\Base\DiaporamaImageCreateForm as BaseDiaporamaImageCreateForm;

/**
 * Class DiaporamaImageCreateForm
 * @package Diaporamas\Form
 */
class DiaporamaImageCreateForm extends BaseDiaporamaImageCreateForm
{
    public function getTranslationKeys()
    {
        return array(
            "diaporama_id" => "Diaporama id",
            "file" => "File",
            "visible" => "Visible",
            "title" => "Title",
            "description" => "Description",
            "chapo" => "Chapo",
            "postscriptum" => "Postscriptum",
        );
    }
}
