<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Form;

use Diaporamas\Form\Base\DiaporamaCreateForm as BaseDiaporamaCreateForm;

/**
 * Class DiaporamaCreateForm
 * @package Diaporamas\Form
 */
class DiaporamaCreateForm extends BaseDiaporamaCreateForm
{
    public function getTranslationKeys()
    {
        return array(
            "title" => "Title",
            "shortcode" => "Shortcode",
            "diaporama_type_id" => "Diaporama type id",
            "entity_id" => "Entity id",
        );
    }
}
