<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Form;

use Diaporamas\Form\Type\DiaporamaIdType;
use Diaporamas\Form\Type\DiaporamaImageIdType;
use Thelia\Form\Image\ImageModification;

/**
 * Class DiaporamaImageUpdateForm
 * @package Diaporamas\Form
 */
class DiaporamaImageUpdateForm extends ImageModification
{
    const FORM_NAME = "diaporama_image_update";

    public function getName()
    {
        return static::FORM_NAME;
    }

    public function buildForm()
    {
        parent::buildForm();
        $this->formBuilder
            ->add("id", DiaporamaImageIdType::TYPE_NAME)
            ->add("diaporama_id", DiaporamaIdType::TYPE_NAME)
        ;
    }
}
