<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Form;

use Diaporamas\Form\Base\DiaporamaUpdateForm as BaseDiaporamaUpdateForm;

/**
 * Class DiaporamaUpdateForm
 * @package Diaporamas\Form
 */
class DiaporamaUpdateForm extends BaseDiaporamaUpdateForm
{
    public function getTranslationKeys()
    {
        return array(
            "id" => "id",
            "title" => "title",
            "shortcode" => "shortcode",
        );
    }
}
