<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Form;

use Diaporamas\Form\Base\DiaporamaImageCreateForm as BaseDiaporamaImageCreateForm;

/**
 * Class DiaporamaImageCreateForm
 * @package Diaporamas\Form
 */
class DiaporamaImageCreateForm extends BaseDiaporamaImageCreateForm
{
    public function getTranslationKeys()
    {
        return array(
            "diaporama_id" => "Diaporama id",
            "diaporama_type_id" => "Diaporama type id",
            "entity_id" => "Entity id",
        );
    }
}
