<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Form;

use Diaporamas\Form\Base\DiaporamaTypeUpdateForm as BaseDiaporamaTypeUpdateForm;

/**
 * Class DiaporamaTypeUpdateForm
 * @package Diaporamas\Form
 */
class DiaporamaTypeUpdateForm extends BaseDiaporamaTypeUpdateForm
{
    public function getTranslationKeys()
    {
        return array(
            "id" => "id",
            "code" => "code",
            "title" => "title",
        );
    }
}
