<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Form;

use Diaporamas\Form\Base\DiaporamaTypeCreateForm as BaseDiaporamaTypeCreateForm;

/**
 * Class DiaporamaTypeCreateForm
 * @package Diaporamas\Form
 */
class DiaporamaTypeCreateForm extends BaseDiaporamaTypeCreateForm
{
    public function getTranslationKeys()
    {
        return array(
            "code" => "Code",
            "title" => "Title",
        );
    }
}
