<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Loop\Base;

use Propel\Runtime\ActiveQuery\Criteria;
use Thelia\Core\Template\Element\BaseLoop;
use Thelia\Core\Template\Element\LoopResult;
use Thelia\Core\Template\Element\LoopResultRow;
use Thelia\Core\Template\Element\PropelSearchLoopInterface;
use Thelia\Core\Template\Loop\Argument\Argument;
use Thelia\Core\Template\Loop\Argument\ArgumentCollection;
use Thelia\Type\BooleanOrBothType;
use Diaporamas\Model\DiaporamaImageQuery;

/**
 * Class DiaporamaImage
 * @package Diaporamas\Loop\Base
 * @author TheliaStudio
 */
class DiaporamaImage extends BaseLoop implements PropelSearchLoopInterface
{

    /**
     * @param LoopResult $loopResult
     *
     * @return LoopResult
     */
    public function parseResults(LoopResult $loopResult)
    {
        /** @var \Diaporamas\Model\DiaporamaImage $entry */
        foreach ($loopResult->getResultDataCollection() as $entry) {
            $row = new LoopResultRow($entry);

            $row
                ->set("ID", $entry->getId())
                ->set("DIAPORAMA_ID", $entry->getDiaporamaId())
                ->set("DIAPORAMA_TYPE_ID", $entry->getDiaporamaTypeId())
                ->set("ENTITY_ID", $entry->getEntityId())
                ->set("POSITION", $entry->getPosition())
            ;

            $this->addMoreResults($row, $entry);

            $loopResult->addRow($row);
        }

        return $loopResult;
    }

    /**
     * Definition of loop arguments
     *
     * example :
     *
     * public function getArgDefinitions()
     * {
     *  return new ArgumentCollection(
     *
     *       Argument::createIntListTypeArgument('id'),
     *           new Argument(
     *           'ref',
     *           new TypeCollection(
     *               new Type\AlphaNumStringListType()
     *           )
     *       ),
     *       Argument::createIntListTypeArgument('category'),
     *       Argument::createBooleanTypeArgument('new'),
     *       ...
     *   );
     * }
     *
     * @return \Thelia\Core\Template\Loop\Argument\ArgumentCollection
     */
    protected function getArgDefinitions()
    {
        return new ArgumentCollection(
            Argument::createIntListTypeArgument("id"),
            Argument::createIntListTypeArgument("diaporama_id"),
            Argument::createIntListTypeArgument("diaporama_type_id"),
            Argument::createIntListTypeArgument("entity_id"),
            Argument::createIntListTypeArgument("position"),
            Argument::createEnumListTypeArgument(
                "order",
                [
                    "id",
                    "id-reverse",
                    "diaporama_id",
                    "diaporama_id-reverse",
                    "diaporama_type_id",
                    "diaporama_type_id-reverse",
                    "entity_id",
                    "entity_id-reverse",
                    "manual",
                    "manual-reverse",
                ],
                "manual"
            )
        );
    }

    /**
     * this method returns a Propel ModelCriteria
     *
     * @return \Propel\Runtime\ActiveQuery\ModelCriteria
     */
    public function buildModelCriteria()
    {
        $query = new DiaporamaImageQuery();

        if (null !== $id = $this->getId()) {
            $query->filterById($id);
        }

        if (null !== $diaporama_id = $this->getDiaporamaId()) {
            $query->filterByDiaporamaId($diaporama_id);
        }

        if (null !== $diaporama_type_id = $this->getDiaporamaTypeId()) {
            $query->filterByDiaporamaTypeId($diaporama_type_id);
        }

        if (null !== $entity_id = $this->getEntityId()) {
            $query->filterByEntityId($entity_id);
        }

        if (null !== $position = $this->getPosition()) {
            $query->filterByPosition($position);
        }

        foreach ($this->getOrder() as $order) {
            switch ($order) {
                case "id":
                    $query->orderById();
                    break;
                case "id-reverse":
                    $query->orderById(Criteria::DESC);
                    break;
                case "diaporama_id":
                    $query->orderByDiaporamaId();
                    break;
                case "diaporama_id-reverse":
                    $query->orderByDiaporamaId(Criteria::DESC);
                    break;
                case "diaporama_type_id":
                    $query->orderByDiaporamaTypeId();
                    break;
                case "diaporama_type_id-reverse":
                    $query->orderByDiaporamaTypeId(Criteria::DESC);
                    break;
                case "entity_id":
                    $query->orderByEntityId();
                    break;
                case "entity_id-reverse":
                    $query->orderByEntityId(Criteria::DESC);
                    break;
                case "manual":
                    $query->orderByPosition();
                    break;
                case "manual-reverse":
                    $query->orderByPosition(Criteria::DESC);
                    break;
            }
        }

        return $query;
    }

    protected function addMoreResults(LoopResultRow $row, $entryObject)
    {
    }
}
