<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Event\Module;

use Diaporamas\Event\Module\Base\DiaporamasEvents as BaseDiaporamasEvents;

/**
 * Class DiaporamasEvents
 * @package Diaporamas\Event\Module
 * @author TheliaStudio
 */
class DiaporamasEvents extends BaseDiaporamasEvents
{
}
