<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Event\Base;

use Thelia\Core\Event\ActionEvent;
use Diaporamas\Model\Diaporama;

/**
* Class DiaporamaEvent
* @package Diaporamas\Event\Base
* @author TheliaStudio
*/
class DiaporamaEvent extends ActionEvent
{
    protected $id;
    protected $title;
    protected $shortcode;
    protected $diaporamaTypeId;
    protected $entityId;
    protected $diaporama;
    protected $locale;

    public function getLocale()
    {
        return $this->locale;
    }

    public function setLocale($v)
    {
        $this->locale = $v;

        return $this;
    }

    public function getId()
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    public function getShortcode()
    {
        return $this->shortcode;
    }

    public function setShortcode($shortcode)
    {
        $this->shortcode = $shortcode;

        return $this;
    }

    public function getDiaporamaTypeId()
    {
        return $this->diaporamaTypeId;
    }

    public function setDiaporamaTypeId($diaporamaTypeId)
    {
        $this->diaporamaTypeId = $diaporamaTypeId;

        return $this;
    }

    public function getEntityId()
    {
        return $this->entityId;
    }

    public function setEntityId($entityId)
    {
        $this->entityId = $entityId;

        return $this;
    }

    public function getDiaporama()
    {
        return $this->diaporama;
    }

    public function setDiaporama(Diaporama $diaporama)
    {
        $this->diaporama = $diaporama;

        return $this;
    }
}
