<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Event\Base;

use Diaporamas\Event\Module\DiaporamasEvents as ChildDiaporamasEvents;

/*
 * Class DiaporamaImageEvents
 * @package Diaporamas\Event\Base
 * @author TheliaStudio
 */
class DiaporamaImageEvents
{
    const CREATE = ChildDiaporamasEvents::DIAPORAMA_IMAGE_CREATE;
    const UPDATE = ChildDiaporamasEvents::DIAPORAMA_IMAGE_UPDATE;
    const DELETE = ChildDiaporamasEvents::DIAPORAMA_IMAGE_DELETE;
    const UPDATE_POSITION = ChildDiaporamasEvents::DIAPORAMA_IMAGE_UPDATE_POSITION;
    const TOGGLE_VISIBILITY = ChildDiaporamasEvents::DIAPORAMA_IMAGE_TOGGLE_VISIBILITY;
}
