<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Event\Base;

use Thelia\Core\Event\ActionEvent;
use Diaporamas\Model\DiaporamaType;

/**
* Class DiaporamaTypeEvent
* @package Diaporamas\Event\Base
* @author TheliaStudio
*/
class DiaporamaTypeEvent extends ActionEvent
{
    protected $id;
    protected $code;
    protected $title;
    protected $path;
    protected $diaporamaType;
    protected $locale;

    public function getLocale()
    {
        return $this->locale;
    }

    public function setLocale($v)
    {
        $this->locale = $v;

        return $this;
    }

    public function getId()
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    public function getCode()
    {
        return $this->code;
    }

    public function setCode($code)
    {
        $this->code = $code;

        return $this;
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    public function getPath()
    {
        return $this->path;
    }

    public function setPath($path)
    {
        $this->path = $path;

        return $this;
    }

    public function getDiaporamaType()
    {
        return $this->diaporamaType;
    }

    public function setDiaporamaType(DiaporamaType $diaporamaType)
    {
        $this->diaporamaType = $diaporamaType;

        return $this;
    }
}
