<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Event\Base;

use Diaporamas\Event\Module\DiaporamasEvents as ChildDiaporamasEvents;

/*
 * Class DiaporamaTypeEvents
 * @package Diaporamas\Event\Base
 * @author TheliaStudio
 */
class DiaporamaTypeEvents
{
    const CREATE = ChildDiaporamasEvents::DIAPORAMA_TYPE_CREATE;
    const UPDATE = ChildDiaporamasEvents::DIAPORAMA_TYPE_UPDATE;
    const DELETE = ChildDiaporamasEvents::DIAPORAMA_TYPE_DELETE;
}
