<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Event\Base;

use Thelia\Core\Event\ActionEvent;
use Diaporamas\Model\DiaporamaImage;

/**
* Class DiaporamaImageEvent
* @package Diaporamas\Event\Base
* @author TheliaStudio
*/
class DiaporamaImageEvent extends ActionEvent
{
    protected $id;
    protected $diaporamaId;
    protected $diaporamaTypeId;
    protected $entityId;
    protected $position;
    protected $diaporamaImage;

    public function getId()
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    public function getDiaporamaId()
    {
        return $this->diaporamaId;
    }

    public function setDiaporamaId($diaporamaId)
    {
        $this->diaporamaId = $diaporamaId;

        return $this;
    }

    public function getDiaporamaTypeId()
    {
        return $this->diaporamaTypeId;
    }

    public function setDiaporamaTypeId($diaporamaTypeId)
    {
        $this->diaporamaTypeId = $diaporamaTypeId;

        return $this;
    }

    public function getEntityId()
    {
        return $this->entityId;
    }

    public function setEntityId($entityId)
    {
        $this->entityId = $entityId;

        return $this;
    }

    public function getPosition()
    {
        return $this->position;
    }

    public function setPosition($position)
    {
        $this->position = $position;

        return $this;
    }

    public function getDiaporamaImage()
    {
        return $this->diaporamaImage;
    }

    public function setDiaporamaImage(DiaporamaImage $diaporamaImage)
    {
        $this->diaporamaImage = $diaporamaImage;

        return $this;
    }
}
