<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Form\Type\Base;

use Thelia\Core\Form\Type\Field\AbstractIdType;
use Diaporamas\Model\DiaporamaQuery;

/**
 * Class Diaporama
 * @package Diaporamas\Form\Base
 * @author TheliaStudio
 */
class DiaporamaIdType extends AbstractIdType
{
    const TYPE_NAME = "diaporama_id";

    protected function getQuery()
    {
        return new DiaporamaQuery();
    }

    public function getName()
    {
        return static::TYPE_NAME;
    }
}
