<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Controller;

use Diaporamas\Controller\Base\DiaporamaTypeController as BaseDiaporamaTypeController;

/**
 * Class DiaporamaTypeController
 * @package Diaporamas\Controller
 */
class DiaporamaTypeController extends BaseDiaporamaTypeController
{
}
