<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Controller;

use Diaporamas\Controller\Base\DiaporamaImageController as BaseDiaporamaImageController;

/**
 * Class DiaporamaImageController
 * @package Diaporamas\Controller
 */
class DiaporamaImageController extends BaseDiaporamaImageController
{
}
