<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Diaporamas\Action\Base;

use Diaporamas\Model\Map\DiaporamaTypeTableMap;
use Diaporamas\Event\DiaporamaTypeEvent;
use Diaporamas\Event\DiaporamaTypeEvents;
use Diaporamas\Model\DiaporamaTypeQuery;
use Diaporamas\Model\DiaporamaType;
use Thelia\Action\BaseAction;
use Thelia\Core\Event\ToggleVisibilityEvent;
use Thelia\Core\Event\UpdatePositionEvent;
use Propel\Runtime\Propel;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Thelia\Core\Event\TheliaEvents;
use \Thelia\Core\Event\TheliaFormEvent;

/**
 * Class DiaporamaTypeAction
 * @package Diaporamas\Action
 * @author TheliaStudio
 */
class DiaporamaTypeAction extends BaseAction implements EventSubscriberInterface
{
    public function create(DiaporamaTypeEvent $event)
    {
        $this->createOrUpdate($event, new DiaporamaType());
    }

    public function update(DiaporamaTypeEvent $event)
    {
        $model = $this->getDiaporamaType($event);

        $this->createOrUpdate($event, $model);
    }

    public function delete(DiaporamaTypeEvent $event)
    {
        $this->getDiaporamaType($event)->delete();
    }

    protected function createOrUpdate(DiaporamaTypeEvent $event, DiaporamaType $model)
    {
        $con = Propel::getConnection(DiaporamaTypeTableMap::DATABASE_NAME);
        $con->beginTransaction();

        try {
            $model->setLocale($event->getLocale());

            if (null !== $id = $event->getId()) {
                $model->setId($id);
            }

            if (null !== $code = $event->getCode()) {
                $model->setCode($code);
            }

            if (null !== $title = $event->getTitle()) {
                $model->setTitle($title);
            }

            if (null !== $path = $event->getPath()) {
                $model->setPath($path);
            }

            $model->save($con);

            $con->commit();
        } catch (\Exception $e) {
            $con->rollback();

            throw $e;
        }

        $event->setDiaporamaType($model);
    }

    protected function getDiaporamaType(DiaporamaTypeEvent $event)
    {
        $model = DiaporamaTypeQuery::create()->findPk($event->getId());

        if (null === $model) {
            throw new \RuntimeException(sprintf(
                "The 'diaporama_type' id '%d' doesn't exist",
                $event->getId()
            ));
        }

        return $model;
    }

    public function beforeCreateFormBuild(TheliaFormEvent $event)
    {
    }

    public function beforeUpdateFormBuild(TheliaFormEvent $event)
    {
    }

    public function afterCreateFormBuild(TheliaFormEvent $event)
    {
    }

    public function afterUpdateFormBuild(TheliaFormEvent $event)
    {
    }

    /**
     * Returns an array of event names this subscriber wants to listen to.
     *
     * The array keys are event names and the value can be:
     *
     *  * The method name to call (priority defaults to 0)
     *  * An array composed of the method name to call and the priority
     *  * An array of arrays composed of the method names to call and respective
     *    priorities, or 0 if unset
     *
     * For instance:
     *
     *  * array('eventName' => 'methodName')
     *  * array('eventName' => array('methodName', $priority))
     *  * array('eventName' => array(array('methodName1', $priority), array('methodName2'))
     *
     * @return array The event names to listen to
     *
     * @api
     */
    public static function getSubscribedEvents()
    {
        return array(
            DiaporamaTypeEvents::CREATE => array("create", 128),
            DiaporamaTypeEvents::UPDATE => array("update", 128),
            DiaporamaTypeEvents::DELETE => array("delete", 128),
            TheliaEvents::FORM_BEFORE_BUILD . ".diaporama_type_create" => array("beforeCreateFormBuild", 128),
            TheliaEvents::FORM_BEFORE_BUILD . ".diaporama_type_update" => array("beforeUpdateFormBuild", 128),
            TheliaEvents::FORM_AFTER_BUILD . ".diaporama_type_create" => array("afterCreateFormBuild", 128),
            TheliaEvents::FORM_AFTER_BUILD . ".diaporama_type_update" => array("afterUpdateFormBuild", 128),
        );
    }
}
